<?php

namespace Leopaulo88\Asaas\Enums;

enum CancellationReason: string
{
    case PAYMENT_DELETED = 'PAYMENT_DELETED';
    case PAYMENT_OVERDUE = 'PAYMENT_OVERDUE';
    case PAYMENT_RECEIVED_IN_CASH = 'PAYMENT_RECEIVED_IN_CASH';
    case PAYMENT_REFUNDED = 'PAYMENT_REFUNDED';
    case VALUE_DIVERGENCE_BLOCK = 'VALUE_DIVERGENCE_BLOCK';
    case WALLET_UNABLE_TO_RECEIVE = 'WALLET_UNABLE_TO_RECEIVE';
}
