<?php

namespace Leopaulo88\Asaas\Enums;

enum ChargebackReason: string
{
    case ABSENCE_OF_PRINT = 'ABSENCE_OF_PRINT';
    case ABSENT_CARD_FRAUD = 'ABSENT_CARD_FRAUD';
    case CARD_ACTIVATED_PHONE_TRANSACTION = 'CARD_ACTIVATED_PHONE_TRANSACTION';
    case CARD_FRAUD = 'CARD_FRAUD';
    case CARD_RECOVERY_BULLETIN = 'CARD_RECOVERY_BULLETIN';
    case COMMERCIAL_DISAGREEMENT = 'COMMERCIAL_DISAGREEMENT';
    case COPY_NOT_RECEIVED = 'COPY_NOT_RECEIVED';
    case CREDIT_OR_DEBIT_PRESENTATION_ERROR = 'CREDIT_OR_DEBIT_PRESENTATION_ERROR';
    case DIFFERENT_PAY_METHOD = 'DIFFERENT_PAY_METHOD';
    case FRAUD = 'FRAUD';
    case INCORRECT_TRANSACTION_VALUE = 'INCORRECT_TRANSACTION_VALUE';
    case INVALID_CURRENCY = 'INVALID_CURRENCY';
    case INVALID_DATA = 'INVALID_DATA';
    case LATE_PRESENTATION = 'LATE_PRESENTATION';
    case LOCAL_REGULATORY_OR_LEGAL_DISPUTE = 'LOCAL_REGULATORY_OR_LEGAL_DISPUTE';
    case MULTIPLE_ROCS = 'MULTIPLE_ROCS';
    case ORIGINAL_CREDIT_TRANSACTION_NOT_ACCEPTED = 'ORIGINAL_CREDIT_TRANSACTION_NOT_ACCEPTED';
    case OTHER_ABSENT_CARD_FRAUD = 'OTHER_ABSENT_CARD_FRAUD';
    case PROCESS_ERROR = 'PROCESS_ERROR';
    case RECEIVED_COPY_ILLEGIBLE_OR_INCOMPLETE = 'RECEIVED_COPY_ILLEGIBLE_OR_INCOMPLETE';
    case RECURRENCE_CANCELED = 'RECURRENCE_CANCELED';
    case REQUIRED_AUTHORIZATION_NOT_GRANTED = 'REQUIRED_AUTHORIZATION_NOT_GRANTED';
    case RIGHT_OF_FULL_RECOURSE_FOR_FRAUD = 'RIGHT_OF_FULL_RECOURSE_FOR_FRAUD';
    case SALE_CANCELED = 'SALE_CANCELED';
    case SERVICE_DISAGREEMENT_OR_DEFECTIVE_PRODUCT = 'SERVICE_DISAGREEMENT_OR_DEFECTIVE_PRODUCT';
    case SERVICE_NOT_RECEIVED = 'SERVICE_NOT_RECEIVED';
    case SPLIT_SALE = 'SPLIT_SALE';
    case TRANSFERS_OF_DIVERSE_RESPONSIBILITIES = 'TRANSFERS_OF_DIVERSE_RESPONSIBILITIES';
    case UNQUALIFIED_CAR_RENTAL_DEBIT = 'UNQUALIFIED_CAR_RENTAL_DEBIT';
    case USA_CARDHOLDER_DISPUTE = 'USA_CARDHOLDER_DISPUTE';
    case VISA_FRAUD_MONITORING_PROGRAM = 'VISA_FRAUD_MONITORING_PROGRAM';
    case WARNING_BULLETIN_FILE = 'WARNING_BULLETIN_FILE';
}
