<?php

namespace Leopaulo88\Asaas\Enums;

enum RefundsStatus: string
{
    case PENDING = 'PENDING';
    case AWAITING_CRITICAL_ACTION_AUTHORIZATION = 'AWAITING_CRITICAL_ACTION_AUTHORIZATION';
    case AWAITING_CUSTOMER_EXTERNAL_AUTHORIZATION = 'AWAITING_CUSTOMER_EXTERNAL_AUTHORIZATION';
    case CANCELLED = 'CANCELLED';
    case DONE = 'DONE';
}
